### ISSUE TITLE
When editing/modifying a Pre-existing information in the new GUI, the form-fields come out to be empty (Nightlies 5/22/2018)

### ISSUE THREAD

**Issue by vaibhav-rbs** [freenas/freenas#1258]
https://redmine.ixsystems.com/issues/33897

**Comment by vaibhav-rbs** [comment]
https://github.com/freenas/webui/pull/784

**Comment by william-gr** [comment]
Shouldnt this issue be on webui repo?

**Comment by vaibhav-rbs** [comment]
oops thats correct I accidentally opened this issue here. closing it out.
